--LAB-9

--SUB QUERIES

CREATE TABLE STUDENT_DATA
(
	NO INT,
	Name VARCHAR(25),
	City VARCHAR(25),
	DID	INT
)

CREATE TABLE ACADEMIC
(
	Rno INT,
	SPI DECIMAL(2,1),
	Bklog INT
)

CREATE TABLE DEPARTMENT
(
	DID INT,
	DName VARCHAR(25)
)


INSERT INTO STUDENT_DATA
VALUES
(101, 'Raju', 'Rajkot', 10),
(102, 'Amit', 'Ahmedabad', 20),
(103, 'Sanjay', 'Baroda', 40),
(104, 'Neha', 'Rajkot', 20),
(105, 'Meera', 'Ahmedabad', 30),
(106, 'Mahesh', 'Baroda', 10)


INSERT INTO ACADEMIC
VALUES
(101, 8.8, 0),
(102, 9.2, 2),
(103, 7.6, 1),
(104, 8.2, 4),
(105, 7.0, 2),
(106, 8.9, 3)


INSERT INTO DEPARTMENT
VALUES
(10, 'Computer'),
(20, 'Electrical'),
(30, 'Mechanical'),
(40, 'Civil')


--PART-A

--1.
	SELECT * FROM STUDENT_DATA
	WHERE DID IN (SELECT DID FROM DEPARTMENT
				 WHERE DName = 'Computer')

--2.
	SELECT Name FROM STUDENT_DATA
	WHERE NO IN (SELECT Rno FROM ACADEMIC WHERE SPI > 8)

--3.
	SELECT * FROM STUDENT_DATA
	WHERE CITY = 'Rajkot' AND DID IN (SELECT DID FROM DEPARTMENT WHERE DName = 'Computer')

--4.
	SELECT COUNT(*) FROM STUDENT_DATA 
	WHERE DID IN (SELECT DID FROM DEPARTMENT WHERE DName = 'Electrical');

--5.
	SELECT Name FROM STUDENT_DATA
	WHERE NO IN (SELECT Rno FROM ACADEMIC WHERE SPI = (SELECT MAX(SPI) FROM ACADEMIC))

--6.
	SELECT * FROM STUDENT_DATA
	WHERE NO IN (SELECT Rno FROM ACADEMIC WHERE Bklog > 1)

--PART-B

--1.
	SELECT Name FROM STUDENT_DATA
	WHERE DID IN (SELECT DID FROM DEPARTMENT WHERE DName IN ('Computer','Mechanical'))

--2.
	SELECT Name FROM STUDENT_DATA
	WHERE DID IN (SELECT DID FROM STUDENT_DATA WHERE NO =102)

--PART-C

--1.

	SELECT Name FROM STUDENT_DATA
	WHERE NO IN (SELECT RNO FROM ACADEMIC WHERE SPI>9) AND
	DID= (SELECT DID FROM DEPARTMENT WHERE DNAME='ELECTRICAL')


--2.
	SELECT NAME FROM STUDENT_DATA
	WHERE NO=(SELECT RNO FROM ACADEMIC
	WHERE SPI=(SELECT MAX(SPI)	
			   FROM ACADEMIC
			   WHERE SPI< (SELECT MAX(SPI) FROM ACADEMIC)));


	SELECT Name FROM STUDENT_DATA WHERE NO=(SELECT RNO FROM ACADEMIC
	WHERE SPI=( SELECT TOP 1 SPI
	FROM (SELECT DISTINCT TOP 2 SPI FROM ACADEMIC ORDER BY SPI DESC) AS TEMP
	ORDER BY SPI ASC))

--3.
	SELECT Name FROM STUDENT_DATA
	WHERE NO IN (SELECT Rno FROM ACADEMIC WHERE SPI = 9.2)

--SET OPERATORS

--PART-A


CREATE TABLE COMPUTER
(
	RollNo INT,
	Name	VARCHAR(25)
)

CREATE TABLE ELECTRICAL
(
	RollNo INT,
	Name	VARCHAR(25)
)

INSERT INTO COMPUTER
VALUES
(101, 'Ajay'), 
(109, 'Haresh'),
(115, 'Manish')

INSERT INTO Electrical
VALUES
(105,'Ajay'),
(107,'Mahesh'),
(115,'Manish')

--1.
	SELECT NAME FROM COMPUTER
	UNION
	SELECT NAME FROM ELECTRICAL

--2
	SELECT NAME FROM COMPUTER
	UNION ALL
	SELECT NAME FROM ELECTRICAL

--3	
	SELECT NAME FROM COMPUTER
	INTERSECT
	SELECT NAME FROM ELECTRICAL

--4	
	SELECT NAME FROM COMPUTER	
	EXCEPT	
	SELECT NAME FROM ELECTRICAL

--5
	SELECT NAME FROM ELECTRICAL
	EXCEPT
	SELECT NAME FROM COMPUTER

--6
	SELECT * FROM COMPUTER
	UNION
	SELECT * FROM ELECTRICAL

--7
	SELECT * FROM COMPUTER
	INTERSECT
	SELECT * FROM ELECTRICAL

--PART-B

CREATE TABLE EMP_DATA
(
	EID INT,
	Name VARCHAR(25)	
)

CREATE TABLE CUSTOMER
(
	CID INT,
	Name VARCHAR(25)
)


INSERT INTO EMP_DATA
VALUES
(101,'Ajay'),
(109,'Haresh'),
(115,'Manish')

INSERT INTO CUSTOMER
VALUES
(105,'Ajay'),
(107,'Mahesh'),
(115,'Manish')


--1.
	SELECT NAME FROM EMP_DATA
	UNION
	SELECT NAME FROM CUSTOMER

--2.
	SELECT NAME FROM EMP_DATA
	UNION ALL
	SELECT NAME FROM CUSTOMER

--3.
	SELECT NAME FROM EMP_DATA
	INTERSECT
	SELECT NAME FROM CUSTOMER

--4.
	SELECT NAME FROM EMP_DATA
	EXCEPT
	SELECT NAME FROM CUSTOMER

--5.
	SELECT NAME FROM CUSTOMER
	EXCEPT
	SELECT NAME FROM EMP_DATA

