--CREATE DATABASE LAB_3

--PART-A (INTO OPERATION)

CREATE TABLE Cricket
(
	Name VARCHAR(50),
	City VARCHAR(50),
	Age INT
)

--1.
	SELECT * INTO Worldcup FROM Cricket

--2.
	SELECT Name, City INTO T20 FROM Cricket
	WHERE 1=2

--3.
	SELECT * INTO IPL FROM Cricket
	WHERE 1=2

--PART-B

CREATE TABLE Employee
(
	Name VARCHAR(50),
	City VARCHAR(50),
	Age INT
)


--1.
	SELECT * INTO Employee_detail FROM Employee

--2.
	SELECT Name, City INTO Employee_data FROM Employee
	WHERE 1=2

--3.
	SELECT * INTO Employee_info FROM Employee
	WHERE 1=2


--PART-C

--1.
	INSERT INTO Employee_info(Name, City, Age)
	SELECT Name, City, Age FROM Employee
	WHERE City = 'Rajkot'

--2.
	INSERT INTO Employee_info(Name, City, Age)
	SELECT * FROM Employee
	WHERE Age > 32


--UPDATE OPERATION

--1.
	UPDATE DEPOSIT
	SET AMOUNT = 5000
	WHERE AMOUNT = 3000

--2.
	UPDATE BORROW
	SET BNAME = 'C.G. ROAD'
	WHERE BNAME = 'VRCE' AND CNAME = 'ANIL'

--3
	UPDATE DEPOSIT
	SET ACTNO = 111 , AMOUNT=5000
	WHERE CNAME = 'SANDIP'

--4.
	UPDATE DEPOSIT
	SET AMOUNT = 7000
	WHERE CNAME = 'KRANTI'

--5.
	UPDATE BRANCH
	SET BNAME = 'ANDHERI WEST'
	WHERE BNAME = 'ANDHERI'

--6. 
	UPDATE DEPOSIT
	SET BNAME = 'NEHRU PALACE'
	WHERE CNAME = 'MEHUL'

--7.
	UPDATE DEPOSIT
	SET AMOUNT = 5000
	WHERE ACTNO BETWEEN 103 AND 107

--8.
	UPDATE DEPOSIT
	SET ADATE = '01-APR-1995'
	WHERE CNAME = 'ANIL'

--9.
	UPDATE DEPOSIT
	SET AMOUNT = 10000
	WHERE CNAME = 'MINU'

--10.
	UPDATE DEPOSIT
	SET AMOUNT = 5000, ADATE = '01-APR-1996'
	WHERE CNAME = 'PRMOD' --'PRMOD' IN PLACE OF 'PRAMOD'


--PART-B

--1.
	UPDATE BORROW
	SET AMOUNT = (AMOUNT*0.1)+AMOUNT

--2.
	UPDATE DEPOSIT
	SET AMOUNT = (AMOUNT*0.2)+AMOUNT

--PART-C

--1.
	UPDATE BORROW
	SET AMOUNT = NULL
	WHERE LOANNO = 321

--2.
	UPDATE BORROW
	SET BNAME = NULL
	WHERE BNAME = 'KRANTI'

--3.
	SELECT CNAME FROM BORROW
	WHERE AMOUNT = NULL

--4.
	SELECT * FROM BORROW
	WHERE BNAME != NULL

--5.
	UPDATE BORROW
	SET AMOUNT=5000,BNAME='VRCE',CNAME='Darshan'
	WHERE LOANNO = 481

--6.
	UPDATE DEPOSIT
	SET ADATE = '01-JAN-2021'
	WHERE AMOUNT < 2000

--7.
	UPDATE DEPOSIT
	SET ADATE = NULL, BNAME = 'ANDHERI'
	WHERE ACTNO = 110

