CREATE TABLE STUDENT_INFO
(
	RNo INT,
	Name VARCHAR(25),
	Branch VARCHAR(10),
	SPI DECIMAL(4,2),
	Bklog INT
)

INSERT INTO STUDENT_INFO
VALUES
(101, 'Raju', 'CE', 8.80, 0),
(102, 'Amit', 'CE', 2.20, 3),
(103, 'Sanjay', 'ME', 1.50, 6),
(104, 'Neha', 'EC', 7.65, 1),
(105, 'Meera', 'EE', 5.52, 2),
(106, 'Mahesh', 'EC', 4.50, 3)--1.	CREATE VIEW Personal AS	SELECT * FROM STUDENT_INFO--2.	CREATE VIEW Student_Details AS	SELECT RNo,BRANCH,SPI FROM STUDENT_INFO--3.	CREATE VIEW AcademicData AS	SELECT RNo,NAME, BRANCH FROM STUDENT_INFO--4.	CREATE VIEW Student_bklog AS	SELECT * FROM STUDENT_INFO 	WHERE Bklog > 2--5.	CREATE VIEW Student_Pattern AS	SELECT RNo,NAME,BRANCH FROM STUDENT_INFO	WHERE NAME LIKE '____'--6.	INSERT INTO AcademicData(RNo,Name,Branch)	VALUES	(107, 'Meet', 'ME')--7.	UPDATE Student_Details	SET Branch = 'ME'	WHERE RNo = 102 AND Branch = 'CE'--8.	DELETE FROM AcademicData	WHERE RNo = 104--PART-B--1.	CREATE VIEW VIEWB1 AS	SELECT * FROM STUDENT_INFO	WHERE SPI > 8.5--2.	CREATE VIEW VIEWB2 AS	SELECT * FROM STUDENT_INFO	WHERE Bklog = 0--3.	CREATE VIEW Computerview AS	SELECT * FROM STUDENT_INFO	WHERE Branch = 'CE'--PART-C--1.	CREATE VIEW Result_EC AS	SELECT NAME,SPI FROM STUDENT_INFO	WHERE SPI < 5 AND Branch = 'EC'--2.	UPDATE Result_EC	SET SPI = 4.90	WHERE NAME = 'Mahesh'--3.	CREATE VIEW Stu_Bklog AS	SELECT RNo,Name,Bklog FROM STUDENT_INFO	WHERE Name LIKE 'M%' AND Bklog > 5--4.	DROP VIEW Computerview	