--ALTER OPERATION

--1.
	ALTER TABLE DEPOSIT
	ADD City VARCHAR(20),Pincode INT

--2.
	ALTER TABLE DEPOSIT
	ALTER COLUMN CNAME VARCHAR(35)

--3.
	ALTER TABLE DEPOSIT
	ALTER COLUMN AMOUNT INT

--4.
	SP_RENAME 'DEPOSIT.ActNo','ANO'

--5.
	ALTER TABLE DEPOSIT
	DROP COLUMN City

--6.
	SP_RENAME 'DEPOSIT','DEPOSIT_DETAIL'

--PART-B

--1.
	SP_RENAME 'DEPOSIT_DETAIL.ADATE','AOPENDATE' 

--2.
	ALTER TABLE DEPOSIT_DETAIL
	DROP COLUMN AOPENDATE

--3.
	SP_RENAME 'DEPOSIT_DETAIL.CNAME','CustomerName'


--PART-C

--1.
	CREATE TABLE Student
	(
		Enrollment_No	VARCHAR(20),
		Name	VARCHAR(25),
		CPI		DECIMAL(5,2),
		Birthdate	DATETIME
	)

--1.
	ALTER TABLE Student
	ADD City VARCHAR(20), Backlog INT

--2.
	ALTER TABLE Student
	ALTER COLUMN NAME VARCHAR(35)

--3.
	ALTER TABLE Student
	ALTER COLUMN CPI INT

--4.
	SP_RENAME 'Student.Enrollment_No','ENO','COLUMN'

--5.
	ALTER TABLE Student
	DROP COLUMN City

--6.
	SP_RENAME 'STUDENT','STUDENT_MASTER'



--DELETE, TRUNCATE, DROP OPERATION

--1.
	DELETE FROM DEPOSIT_DETAIL
	WHERE AMOUNT >= 4000

--2.
	DELETE FROM DEPOSIT_DETAIL
	WHERE BNAME = 'CHANDI'

--3.
	DELETE FROM DEPOSIT_DETAIL
	WHERE ANO > 105

--4.
	TRUNCATE TABLE DEPOSIT_DETAIL

--5.
	DROP TABLE DEPOSIT_DETAIL

--PART-B


CREATE TABLE Employee_Master
(
	EmpNo	INT,
	EmpName	VARCHAR(25),
	JoiningDate	DATETIME,
	Salary	DECIMAL (8,2),
	City	VARCHAR(20)
)


INSERT INTO Employee_Master
VALUES
(101, 'Keyur', '5-JAN-02', 12000.00, 'Rajkot'),
(102,'Hardik','15-FEB-04', 14000.00	,'Ahmedabad'),
(103,'Kajal','14-MAR-06', 15000.00	,'Baroda'),
(104,'Bhoomi','23-JUN-05', 12500.00	,'Ahmedabad'),
(102,'Harmit','15-FEB-04', 14000.00	,'Rajkot')


--1.
	DELETE FROM Employee_MASTER 
	WHERE SALARY >= 14000

--2.
	DELETE FROM Employee_MASTER 
	WHERE City = 'RAJKOT'

--3.
	DELETE FROM Employee_MASTER 
	WHERE JoiningDate > '01-JAN-2007'

--4.
	DELETE FROM Employee_Master
	WHERE JoiningDate IS NULL AND NAME IS NOT NULL

--5.
	DELETE FROM Employee_Master
	WHERE Salary = ((20000*50)/100)

--6.
	DELETE FROM Employee_Master
	WHERE City IS NOT NULL
 
--7.
	TRUNCATE TABLE Employee_MASTER 

--8.
	DROP TABLE Employee_MASTER 


